const express = require('express')
const server = express()
const inventory = require('./routers/inventory')
const statuses = require('./routers/statuses')
const plants = require('./routers/plants')
const auth = require('./routers/auth')
const cors = require('cors')
const helmet = require('helmet')
server.use(express.json())
server.use(cors())
server.use(helmet())
server.use('/api/auth', auth)
server.use('/api/inventory', inventory)
server.use('/api/statuses', statuses)
server.use('/api/plants', plants)
server.all('/', (req, res) => res.send('Server is live'))

module.exports = server
